name: TheDannJK_Worlds
version: '1.0'
main: p.theDannJK_Worlds.TheDannJK_Worlds
api-version: '1.19'
commands:
  createworld:
    description: Crea un nuevo mundo.
  setspawn:
    description: Establece el punto de spawn en el mundo actual.
  tpworld:
    description: Teletransporta a un jugador a otro mundo.
  reloadworlds:
    description: Recarga la configuración del plugin.
  editportal:
    description: Edita los parámetros de un portal.
